
let laureates =
  [
    {
      Name: 'Joanna Markowicz',
      School: 'Politechnika Rzeszowska',
      Reward: 'CDN$4,000.00',
      Year: '2021',
    },
    {
      Name: 'Oliwia Jeznach',
      School: 'Instytut Podstawowych Problemów Techniki PAN',
      Reward: 'CDN$4,000.00',
      Year: '2021',
    },
    {
      Name: 'Adrian Arendowski',
      School: 'Politechnika Rzeszowska',
      Reward: 'CDN$4,000.00',
      Year: '2020',
    },
    {
      Name: 'Krzysztof Jankowski',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2020',
    },
    {
      Name: 'Monika Budnicka',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2019',
    },
    {
      Name: 'Magdalena Flont',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2019',
    },
    {
      Name: 'Agnieszka Uryga',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$4,000.00',
      Year: '2019',
    },
    {
      Name: 'Justyna Kutkowska',
      School: 'Instytutu Immunologii i Terapii Doświadczalnej im. Ludwika Hirszfelda',
      Reward: 'CDN$4,000.00',
      Year: '2018',
    },
    {
      Name: 'Agnieszka Zuchowska',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2018',
    },
    {
      Name: 'Aleksandra Kruk',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2017',
    },
    {
      Name: 'Ewa Bednarczyk',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2017',
    },
    {
      Name: 'Marta Danch-Wierzchowska',
      School: 'Politechnika Śląska',
      Reward: 'CDN$4,000.00',
      Year: '2016',
    },
    {
      Name: 'Marcin Dominik Jukiewicz',
      School: 'Politechnika Poznańska',
      Reward: 'CDN$4,000.00',
      Year: '2016',
    },
    {
      Name: 'Paulina Trzaskowska',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2015',
    },
    {
      Name: 'Bartlomiej Pyciński',
      School: 'Politechnika Śląska',
      Reward: 'CDN$4,000.00',
      Year: '2015',
    },
    {
      Name: 'Radosław Kwapiszewski',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2014',
    },
    {
      Name: 'Bartosz Marcin Krawczyk',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$4,000.00',
      Year: '2014',
    },
    {
      Name: 'Joanna Weżgowiec',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$4,000.00',
      Year: '2013',
    },
    {
      Name: 'Karina Kwapiszewska',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$4,000.00',
      Year: '2013',
    },
    {
      Name: 'Nina Skołucka',
      School: 'Akademia Medyczna Wrocław',
      Reward: 'CDN$4,000.00',
      Year: '2012',
    },
    {
      Name: 'Daniel Milej',
      School: 'Instytut Biocybernetyki i Inżynierii Biomedycznej im. Macieja Nałęcza PAN',
      Reward: 'CDN$4,000.00',
      Year: '2012',
    },
    {
      Name: 'Anna Małgorzata Choromańska',
      School: 'Akademia Medyczna Wrocław',
      Reward: 'CDN$4,000.00',
      Year: '2011',
    },
    {
      Name: 'Michał Krzysztof Kania',
      School: 'Instytut Biocybernetyki i Inżynierii Biomedycznej im. Macieja Nałęcza PAN',
      Reward: 'CDN$4,000.00',
      Year: '2011',
    },
    {
      Name: 'Marek Jan Rojczyk',
      School: 'Politechnika Śląska',
      Reward: 'CDN$4,000.00',
      Year: '2010',
    },
    {
      Name: 'Jacek Stanisław Tutak',
      School: 'Politechnika Rzeszowska',
      Reward: 'CDN$4,000.00',
      Year: '2010',
    },
    {
      Name: 'Małgorzata Anna Kowalska',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$4,000.00',
      Year: '2009',
    },
    {
      Name: 'Anna Maria Janus',
      School: 'Polska Akademia Nauk - Kraków',
      Reward: 'CDN$4,000.00',
      Year: '2009',
    },
    {
      Name: 'Katarzyna A. Wysocka',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$4,000.00',
      Year: '2008',
    },
    {
      Name: 'Maciej Gawlikowski',
      School: 'Politechnika Śląska',
      Reward: 'CDN$4,000.00',
      Year: '2008',
    },
    {
      Name: 'Barbara Kolarik',
      School: 'Politechnika śląska',
      Reward: 'CDN$3,000.00',
      Year: '2007',
    },
    {
      Name: 'Dorota Szczęsna',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$3,000.00',
      Year: '2007',
    },
    {
      Name: 'Ewa Teślak',
      School: 'Politechnika Poznanska',
      Reward: 'CDN$3,000.00',
      Year: '2006',
    },
    {
      Name: 'Paweł Borkowski',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$3,000.00',
      Year: '2006',
    },
    {
      Name: 'Julita Kulbacka',
      School: 'Wrocławska Akademia Medyczna',
      Reward: 'CDN$3,000.00',
      Year: '2005',
    },
    {
      Name: 'Paweł Kuklik',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$3,000.00',
      Year: '2005',
    },
    {
      Name: 'Magdalena Kasprowicz',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$3,000.00',
      Year: '2004',
    },
    {
      Name: 'Janusz Domański',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$3,000.00',
      Year: '2004',
    },
    {
      Name: 'Dariusz Janusek',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$2,500.00',
      Year: '2003',
    },
    {
      Name: 'Małgorzata Wąsowska',
      School: 'Bydgoska Akademia Techniczno-Rolnicza',
      Reward: 'CDN$2,500.00',
      Year: '2003',
    },
    {
      Name: 'Marek Tomasz Kulig',
      School: 'Akademia Górniczo-Hutnicza',
      Reward: 'CDN$2,500.00',
      Year: '2002',
    },
    {
      Name: 'Krzysztof Stanisław Urbaniak',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$2,500.00',
      Year: '2002',
    },
    {
      Name: 'Marek Pawlikowski',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$2,500.00',
      Year: '2001',
    },
    {
      Name: 'Paweł Świercz',
      School: 'Warszawska Akademia Medyczna',
      Reward: 'CDN$2,500.00',
      Year: '2001',
    },
    {
      Name: 'Stanisław Jan Kowalik',
      School: 'Politechnika Warszawska',
      Reward: 'CDN$1,500.00',
      Year: '2000',
    },
    {
      Name: 'Agnieszka Ulatowska-Jarża',
      School: 'Politechnika Wrocławska',
      Reward: 'CDN$1,500.00',
      Year: '2000',
    }];

    export default laureates;